name: Upload to Cloudsmith

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with LFS support)
        uses: actions/checkout@v3
        with:
          lfs: true  # ✅ This pulls Git LFS files too

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Cloudsmith CLI
        run: pip install cloudsmith-cli

      - name: Confirm LFS file exists and is real
        run: |
          ls -lh vault_1.17.5+ent.hsm_linux_amd64.zip
          file vault_1.17.5+ent.hsm_linux_amd64.zip

      - name: Upload to Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          cloudsmith push raw adityatestenv/cloudsmith-cli-test vault_1.17.5+ent.hsm_linux_amd64.zip \
           --name vault_1.17.5+ent.hsm_linux_amd64.zip \
           --version 1.17.5-hsm \
           --summary "Vault Enterprise HSM build for Linux AMD64" \
           --description "HashiCorp Vault 1.17.5+ent.hsm compiled for Linux AMD64 architecture"
